steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-north1-docker.pkg.dev/prisma-extractor/gc-registry-vitalii/app1:$COMMIT_SHA'
      - '-f'
      - 'app1/Dockerfile'
      - 'app1'
options:
  logs_bucket: 'gs://prisma-extractor_cloudbuild'