apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-helm-repro
  namespace: codefresh
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 19.1.0
    helm:
      releaseName: mongo-helm-repro
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-helm-repro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
