apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: monorepo-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          image: nginx:1.25
          ports:
            - containerPort: 80
