# Default values for single-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
app1:
  port: 8002
  image: vitaliicodefresh/app1:develop

app2:
  app1host: http://app1-service/app1
  image: vitaliicodefresh/app2:develop
