apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    owner: vitalii
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
      name: http
  type: ClusterIP