apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-self-manages-argocd
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/vitalii-codefresh/simple-server.git'
    targetRevision: develop
    path: gitops/self-managed-argocd/kustomize
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true