apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-application
  namespace: argocd-sm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/vitalii-codefresh/simple-server.git'
    targetRevision: develop
    path: mongo/mongodb-chart-gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mongo-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true